objective: "lambdarank"
params:
  n_estimators: 1500
  learning_rate: 0.05
  num_leaves: 64
  max_depth: -1
  subsample: 0.8
  colsample_bytree: 0.8
  reg_alpha: 0.0
  reg_lambda: 1.0
  random_state: 42
