seed: 42
paths:
  raw: data/raw
  interim: data/interim
  features: data/features
  artifacts: data/artifacts
split:
  valid_last_years: 3
  test_last_years: 2
target:
  exclude_status: ["DNS", "DNQ"]
  treat_DSQ_as: "exclude"   # "exclude" | "max_pos"
features:
  use_sprint_as_feature: true
  use_circuit_history: true
eval:
  ndcg_k: [3, 5]
